# Generated by Django 5.2.5 on 2025-08-13 01:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='enable_login',
            field=models.BooleanField(default=False, verbose_name='Login Ativado'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='enable_publications',
            field=models.BooleanField(default=False, verbose_name='Publicações Ativadas'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='oab_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número OAB'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='oab_section',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Seccional OAB'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='professional_address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Profissional'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='lawyer_set', related_query_name='lawyer', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='lawyer_set', related_query_name='lawyer', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
