# Generated by Django 5.2.5 on 2025-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lawyer_cpf_lawyer_enable_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='enable_login',
            field=models.BooleanField(default=True, verbose_name='Login Ativado'),
        ),
    ]
