# Generated by Django 5.2.5 on 2025-08-13 00:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='FinancialCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=255, verbose_name='Nome do Caso')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado'), ('PENDING', 'Pendente')], default='OPEN', max_length=10, verbose_name='Status')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='finance.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Caso Financeiro',
                'verbose_name_plural': 'Casos Financeiros',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('payment_method', models.CharField(choices=[('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('CARD', 'Cartão')], max_length=10, verbose_name='Forma de Pagamento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.financialcase', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
