# Generated by Django 5.2.5 on 2025-08-13 01:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_client_city_client_client_area_client_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Pago'), ('PENDING', 'Pendente')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('CARD', 'Cartão')], max_length=10, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
