# Generated by Django 5.2.5 on 2025-08-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_banco_cliente_formapagamento_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='area_cliente_ativa',
            field=models.BooleanField(default=False, verbose_name='Área do Cliente Ativa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha_area_cliente',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha da Área do Cliente'),
        ),
    ]
