# Generated by Django 5.2.5 on 2025-08-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cliente_area_cliente_ativa_cliente_cidade_and_more'),
    ]

    operations = [
    ]
