# Generated by Django 5.2.5 on 2025-08-14 02:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20250813_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='valor',
        ),
        migrations.AddField(
            model_name='receita',
            name='advogado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Advogado'),
        ),
        migrations.AddField(
            model_name='receita',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.banco', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='receita',
            name='condicao_pagamento',
            field=models.CharField(choices=[('a_vista', 'À vista'), ('parcelado', 'Parcelado'), ('entrada_parcelado', 'Entrada + Parcelado')], max_length=20, verbose_name='Condição de Pagamento'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão'),
        ),
        migrations.AddField(
            model_name='receita',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='receita',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='receita',
            name='parcial',
            field=models.BooleanField(default=False, verbose_name='Parcial'),
        ),
        migrations.AddField(
            model_name='receita',
            name='prazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.prazopagamento', verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='rateio_advogado_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rateio_advogado_1', to=settings.AUTH_USER_MODEL, verbose_name='Advogado 1 (Rateio)'),
        ),
        migrations.AddField(
            model_name='receita',
            name='rateio_advogado_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rateio_advogado_2', to=settings.AUTH_USER_MODEL, verbose_name='Advogado 2 (Rateio)'),
        ),
        migrations.AddField(
            model_name='receita',
            name='rateio_advogado_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rateio_advogado_3', to=settings.AUTH_USER_MODEL, verbose_name='Advogado 3 (Rateio)'),
        ),
        migrations.AddField(
            model_name='receita',
            name='rateio_ativo',
            field=models.BooleanField(default=False, verbose_name='Rateio Ativo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='rateio_percentual_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Percentual Advogado 1'),
        ),
        migrations.AddField(
            model_name='receita',
            name='rateio_percentual_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Percentual Advogado 2'),
        ),
        migrations.AddField(
            model_name='receita',
            name='rateio_percentual_3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Percentual Advogado 3'),
        ),
        migrations.AddField(
            model_name='receita',
            name='tipo_demanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.tipodemanda', verbose_name='Tipo de Demanda'),
        ),
        migrations.AddField(
            model_name='receita',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Recebido'),
        ),
        migrations.AddField(
            model_name='receita',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tiporeceita', verbose_name='Tipo de Receita'),
        ),
    ]
