# Generated by Django 5.2.5 on 2025-08-14 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_receita_valor_receita_advogado_receita_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeceita',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
    ]