# Generated by Django 5.2.5 on 2025-08-14 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_add_data_cadastro_to_tipo_receita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiporeceita',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Tipo de Receita', 'verbose_name_plural': 'Tipos de Receita'},
        ),
        migrations.AlterField(
            model_name='tiporeceita',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
