# Generated by Django 5.2.5 on 2025-08-14 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_tiporeceita_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='formapagamento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='prazopagamento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='banco',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='prazopagamento',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='tipodespesa',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
        ),
    ]
