# Generated by Django 5.2.5 on 2025-08-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_banco_agencia_remove_banco_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
