# Generated by Django 5.2.5 on 2025-08-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_atividaderecente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividaderecente',
            name='tipo',
            field=models.CharField(choices=[('cliente_cadastrado', 'Cliente Cadastrado'), ('cliente_desativado', 'Cliente Desativado'), ('audiencia_agendada', 'Audiência Agendada'), ('documento_gerado', 'Documento Gerado'), ('recebimento_confirmado', 'Recebimento Confirmado'), ('tarefa_criada', 'Tarefa Criada'), ('processo_criado', 'Processo Criado'), ('processo_atualizado', 'Processo Atualizado'), ('publicacao_recebida', 'Publicação Recebida')], max_length=30, verbose_name='Tipo'),
        ),
    ]
